### ISSUE TITLE
homepage/icon fields

### ISSUE THREAD

**Issue by jexp** [Nhogs/popoto-neo4j-graph-app#8]
> Michael Hunger [08:45]
> hey, the config entry - for a graph app
> if you change "homepage" to something else than "." it seems to start failing? even if the UI then links to the right homepage,
> 
> could it be that the same setting is used for two purposes? loading assets and pointing to a homepage?
> Oskar Hane [08:47]
> Create react app has hijacked that field to do something it's not supposed to do.
> You can add a manifest.json file in the app root and add a homepage field there instead.
> In 'dist/' folder, that is
> 

see 
https://github.com/neo4j-apps/graph-app-starter/blob/master/examples/basic-create-react-app/public/manifest.json

> Oskar Hane [08:58]
> Yep, that's the file. We'll add the homepage field in that example.

**Comment by Popotojs** [comment]
Ok, I changed this field because I wanted the "About" button to point to project page (like in Neo4j Browser app and a few others)

With homepage to "." Neo4j Desktop opens the app default folder.

![2019-01-09_09h26_32](https://user-images.githubusercontent.com/10779077/50886437-ae5e3880-13f0-11e9-85a0-445abd203f2e.png)

It explains why this update is no more working in Desktop.
